spring:
  datasource:
    url: jdbc:tc:postgresql:15://localhost/testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    com.example.order: DEBUG
    org.springframework.kafka: DEBUG 