spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: orderuser
    password: orderpass
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
        validation:
          mode: none
    open-in-view: false
  
  kafka:
    bootstrap-servers: kafka:29092

logging:
  level:
    com.example.order: DEBUG
    org.springframework.kafka: INFO 